services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-projectmeats_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-WATERMELON1219}
      POSTGRES_DB: ${DB_NAME:-projectmeats_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://${DB_USER:-projectmeats_user}:${DB_PASSWORD:-WATERMELON1219}@db:5432/${DB_NAME:-projectmeats_db}
      - DJANGO_SECRET_KEY=${SECRET_KEY:-your_secure_secret_key}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - CSRF_COOKIE_SECURE=True
      - SECURE_HSTS_SECONDS=31536000
      - SECURE_HSTS_INCLUDE_SUBDOMAINS=True
      - SECURE_HSTS_PRELOAD=True
      - CORS_ALLOWED_ORIGINS=${CORS_ORIGINS:-https://localhost}
      - CSRF_TRUSTED_ORIGINS=${CSRF_ORIGINS:-https://localhost}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - static_files:/app/backend/staticfiles
      - media_files:/app/backend/media
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_BASE_URL=${API_BASE_URL:-https://localhost/api/v1}
      - REACT_APP_ENVIRONMENT=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ${SSL_CERT_PATH:-./ssl}:/etc/nginx/ssl:ro
      - static_files:/var/www/static:ro
      - media_files:/var/www/media:ro
    restart: unless-stopped
    environment:
      - SERVER_NAME=${SERVER_NAME:-your_domain.com}

volumes:
  postgres_data:
  static_files:
  media_files: