# Generated by Django 4.2.7 on 2025-07-29 04:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the analytics record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="Type of action performed (chat, document_upload, entity_extraction, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        help_text="Time taken to process the request in seconds"
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of AI tokens used (if applicable)"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the action completed successfully",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if action failed",
                        null=True,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input data for the action (anonymized)"
                    ),
                ),
                (
                    "output_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Metadata about the output (without sensitive content)",
                    ),
                ),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="User rating for the response (1-5 scale)",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Optional user feedback about the response",
                        null=True,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        help_text="AI provider used (openai, anthropic, mock, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        help_text="Specific AI model used", max_length=100
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chat session if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistant.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Analytics",
                "verbose_name_plural": "Usage Analytics",
                "db_table": "ai_assistant_usage_analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_assistan_user_id_4952d5_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="ai_assistan_action__213249_idx",
                    ),
                    models.Index(
                        fields=["success"], name="ai_assistan_success_67c1d1_idx"
                    ),
                    models.Index(
                        fields=["ai_provider", "-created_at"],
                        name="ai_assistan_ai_prov_a83c82_idx",
                    ),
                    models.Index(
                        fields=["processing_time"],
                        name="ai_assistan_process_48871d_idx",
                    ),
                ],
            },
        ),
    ]
