# Generated by Django 4.2.7 on 2025-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(fields=["name"], name="contact_inf_name_05b51f_idx"),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(fields=["status"], name="contact_inf_status_0a3e54_idx"),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(
                fields=["contact_type"], name="contact_inf_contact_5fda95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(
                fields=["customer"], name="contact_inf_custome_7a7424_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(
                fields=["supplier"], name="contact_inf_supplie_3dda6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(fields=["email"], name="contact_inf_email_dc4f7f_idx"),
        ),
        migrations.AddIndex(
            model_name="contactinfo",
            index=models.Index(
                fields=["status", "contact_type"], name="contact_inf_status_0a43d6_idx"
            ),
        ),
    ]
