# Generated by Django 4.2.7 on 2025-07-08 19:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        help_text="Equivalent to PowerApps pro_po_number field (Purchase Order Number)",
                        max_length=100,
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        help_text="Equivalent to PowerApps pro_item field (Item description)",
                        max_length=500,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Equivalent to PowerApps pro_quantity field (Quantity ordered)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Equivalent to PowerApps pro_priceperunit field (Unit price)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        help_text="Equivalent to PowerApps pro_purchasedate field (Date of purchase)"
                    ),
                ),
                (
                    "fulfillment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_fulfillmentdate field (Expected fulfillment date)",
                        null=True,
                    ),
                ),
                (
                    "customer_documents",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_customerdocuments field (Customer document references)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "supplier_documents",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_supplierdocuments field (Supplier document references)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps pro_customer_lookup field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps pro_supplier_lookup field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "purchase_orders_purchaseorder",
                "ordering": ["-purchase_date", "po_number"],
                "indexes": [
                    models.Index(
                        fields=["po_number"], name="purchase_or_po_numb_3289dd_idx"
                    ),
                    models.Index(
                        fields=["purchase_date"], name="purchase_or_purchas_7cf430_idx"
                    ),
                    models.Index(
                        fields=["status"], name="purchase_or_status_252c5c_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="purchase_or_custome_73fcb1_idx"
                    ),
                    models.Index(
                        fields=["supplier"], name="purchase_or_supplie_7c898c_idx"
                    ),
                ],
            },
        ),
    ]
