# Generated by Django 4.2.7 on 2025-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="customer_documents",
            field=models.FileField(
                blank=True,
                help_text="Equivalent to PowerApps pro_customerdocuments field (Customer document uploads)",
                null=True,
                upload_to="purchase_orders/customer_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_documents",
            field=models.FileField(
                blank=True,
                help_text="Equivalent to PowerApps pro_supplierdocuments field (Supplier document uploads)",
                null=True,
                upload_to="purchase_orders/supplier_documents/",
            ),
        ),
    ]
