# Generated by Django 4.2.7 on 2025-07-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="end_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination plant location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_purchase_orders",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Origin plant location (typically from supplier's plants)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbound_purchase_orders",
                to="plants.plant",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="customer_documents",
            field=models.FileField(
                blank=True,
                help_text="Equivalent to PowerApps pro_customerdocuments field (Customer document uploads)",
                null=True,
                upload_to="purchase_orders/customer_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_documents",
            field=models.FileField(
                blank=True,
                help_text="Equivalent to PowerApps pro_supplierdocuments field (Supplier document uploads)",
                null=True,
                upload_to="purchase_orders/supplier_documents/",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["origin_location"], name="purchase_or_origin__d0d20b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["end_location"], name="purchase_or_end_loc_380a42_idx"
            ),
        ),
    ]
