# Generated by Django 4.2.7 on 2025-07-08 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts_receivables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Equivalent to PowerApps cr7c4_nameofsupplier field (Primary Name)",
                        max_length=850,
                    ),
                ),
                (
                    "credit_application_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_datewhencreditapplicationwassent field",
                        null=True,
                    ),
                ),
                (
                    "delivery_type_profile",
                    models.BooleanField(
                        default=False,
                        help_text="Equivalent to PowerApps cr7c4_profileofsupplierdeliverytype field",
                    ),
                ),
                (
                    "accounts_receivable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_accountsreceivablesid field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="accounts_receivables.accountsreceivable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "suppliers",
                "ordering": ["name"],
            },
        ),
    ]
