# Generated by Django 4.2.7 on 2025-07-08 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPlantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Equivalent to PowerApps pro_supplierplantmapping1 field (Primary Name)",
                        max_length=850,
                    ),
                ),
                (
                    "documents_reference",
                    models.CharField(
                        blank=True,
                        help_text="Document references related to this supplier-plant mapping",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "contact_info",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equivalent to PowerApps Contact Info lookup field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_plant_mappings",
                        to="contacts.contactinfo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps Customer lookup field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_plant_mappings",
                        to="customers.customer",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps Supplier lookup field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plant_mappings",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Plant Mapping",
                "verbose_name_plural": "Supplier Plant Mappings",
                "db_table": "supplier_plant_mappings",
                "ordering": ["name"],
            },
        ),
    ]
