# Generated by Django 4.2.7 on 2025-07-09 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0002_supplierplantmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Equivalent to PowerApps pro_locationname field (Primary Name)",
                        max_length=850,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_address field",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_city field",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_state field",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_zipcode field",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps pro_country field",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps pro_supplier_lookup field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Location",
                "verbose_name_plural": "Supplier Locations",
                "db_table": "supplier_locations",
                "ordering": ["supplier__name", "name"],
            },
        ),
    ]
