# Generated by Django 4.2.7 on 2025-07-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
        ("suppliers", "0002_supplierplantmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierplantmapping",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Equivalent to PowerApps Plant lookup field",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_mappings",
                to="plants.plant",
            ),
        ),
    ]
