# Generated by Django 4.2.7 on 2025-07-09 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0003_supplierplantmapping_plant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the supplier location (Primary Name)",
                        max_length=850,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Physical address of the supplier location",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where the supplier location is situated",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State or province of the supplier location",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal or ZIP code of the supplier location",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country where the supplier location is situated",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("headquarters", "Headquarters"),
                            ("warehouse", "Warehouse"),
                            ("distribution_center", "Distribution Center"),
                            ("processing_plant", "Processing Plant"),
                            ("office", "Office"),
                            ("facility", "Facility"),
                        ],
                        help_text="Type of supplier location (warehouse, office, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Contact person name at this location",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for this location",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address for this location",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this supplier location",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps pro_supplier_lookup field",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Location",
                "verbose_name_plural": "Supplier Locations",
                "db_table": "supplier_locations",
                "ordering": ["supplier__name", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="supplier_lo_name_6a94bc_idx"),
                    models.Index(
                        fields=["supplier"], name="supplier_lo_supplie_2cd030_idx"
                    ),
                    models.Index(
                        fields=["location_type"], name="supplier_lo_locatio_1d6145_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="supplier_lo_city_af3c17_idx"
                    ),
                ],
            },
        ),
    ]
