# Generated by Django 4.2.7 on 2025-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_supplierlocation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="suppliers_name_ed482a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["status"], name="suppliers_status_e3c425_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["delivery_type_profile"], name="suppliers_deliver_9a5a8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["accounts_receivable"], name="suppliers_account_86b6df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["credit_application_date"], name="suppliers_credit__69c2f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["status", "name"], name="suppliers_status_3515bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(fields=["name"], name="supplier_pl_name_d862e9_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(fields=["status"], name="supplier_pl_status_88e03b_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(
                fields=["supplier"], name="supplier_pl_supplie_3cae42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(fields=["plant"], name="supplier_pl_plant_i_50a401_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(
                fields=["customer"], name="supplier_pl_custome_15301c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierplantmapping",
            index=models.Index(
                fields=["supplier", "plant"], name="supplier_pl_supplie_ce3267_idx"
            ),
        ),
    ]
