# Generated by Django 4.2.7 on 2025-07-09 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0002_supplierplantmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Equivalent to PowerApps CreatedOn field",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Equivalent to PowerApps ModifiedOn field",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Equivalent to PowerApps statecode/statuscode fields",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Equivalent to PowerApps cr7c4_plantname field (Primary Name)",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_location field",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("processing", "Processing Plant"),
                            ("warehouse", "Warehouse"),
                            ("distribution", "Distribution Center"),
                            ("cold_storage", "Cold Storage"),
                        ],
                        help_text="Equivalent to PowerApps cr7c4_planttype field (picklist)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "release_number",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_releasenumber field",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "load_pickup_requirements",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_loadpickuprequirements field (multi-select picklist). Comma-separated values.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_storage field (multi-select picklist). Comma-separated values.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps CreatedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps ModifiedBy field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Equivalent to PowerApps OwnerId field",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equivalent to PowerApps cr7c4_supplierid field",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plants",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="plants_plan_name_abe05c_idx"),
                    models.Index(
                        fields=["status"], name="plants_plan_status_a920d9_idx"
                    ),
                    models.Index(
                        fields=["plant_type"], name="plants_plan_plant_t_20e521_idx"
                    ),
                    models.Index(
                        fields=["supplier"], name="plants_plan_supplie_618333_idx"
                    ),
                ],
            },
        ),
    ]
