# Generated by Django 4.2.7 on 2025-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_name_25d5e3_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["status"], name="customers_status_47bd31_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["status", "name"], name="customers_status_7da217_idx"
            ),
        ),
    ]
