# Generated by Django 4.2.7 on 2025-07-08 04:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Equivalent to PowerApps CreatedOn field')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Equivalent to PowerApps ModifiedOn field')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Equivalent to PowerApps statecode/statuscode fields', max_length=20)),
                ('name', models.CharField(help_text='Equivalent to PowerApps cr7c4_names field (Primary Name)', max_length=850)),
                ('email', models.EmailField(blank=True, help_text='Equivalent to PowerApps cr7c4_email field', max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Equivalent to PowerApps cr7c4_phone field', max_length=100, null=True)),
                ('terms', models.CharField(blank=True, help_text='Equivalent to PowerApps cr7c4_terms field', max_length=100, null=True)),
                ('created_by', models.ForeignKey(help_text='Equivalent to PowerApps CreatedBy field', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='Equivalent to PowerApps ModifiedBy field', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Equivalent to PowerApps OwnerId field', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounts Receivable',
                'verbose_name_plural': 'Accounts Receivables',
                'db_table': 'accounts_receivables',
                'ordering': ['name'],
            },
        ),
    ]
